function love.conf(t)
    t.identity = "demo"                   -- 盘存文件夹的名称 (string)
    t.appendidentity = true            -- Search files in source directory before save directory (boolean)
    t.version = "11.0"                -- 此游戏对应的 LÖVE 版本(string)
    t.console = false                  -- 附带控制台 (boolean, Windows only)
    t.accelerometerjoystick = true      -- 通过将其暴露为操纵杆来启用 iOS and Android 上的加速度计 (boolean)
    t.externalstorage = false           -- 设为 True 会使程序在 Android 的外部存储中储存（和在同一目录读取）文件 (boolean) 
    t.gammacorrect = false              -- 当系统支持时，启用伽玛校正渲染 (boolean)
 
    t.audio.mixwithsystem = true        -- 在 LOVE 运行时启用后台播放 (boolean, iOS and Android only)
 
    t.window.title = "Untitled"        -- 程序窗口标题 (string)
    t.window.icon = nil                -- 使用一张游戏目录中的图片作为窗口图标 (string)
    t.window.width = 1280               -- 程序窗口宽 (number)
    t.window.height = 720              -- 程序窗口高 (number)
    t.window.borderless = false        -- 移除所有程序边框的视觉效果 (boolean)
    t.window.resizable = false         -- 允许鼠标拖动调整窗口的宽度和高度 (boolean)
    t.window.minwidth = 1              -- 程序窗口的最小宽度，仅当t.window.resizable = true 时生效 (number)
    t.window.minheight = 1             -- 程序窗口的最小高度，仅当t.window.resizable = true 时生效 (number)
    t.window.fullscreen = true        -- 打开程序后全屏运行游戏 (boolean)
    t.window.fullscreentype = "desktop" -- 全屏的模式，有 "desktop" 桌面全屏 和 "exclusive" 全屏 两种选择 (string)
    t.window.vsync = 1              -- 垂直同步模式 (number)
    t.window.msaa = 0                  -- 多样本采样抗锯齿时的样本数 (number)
    t.window.depth = nil                -- The number of bits per sample in the depth buffer
    t.window.stencil = nil              -- The number of bits per sample in the stencil buffer
    t.window.display = 1               -- 显示器的指示显示窗口 (number)
    t.window.highdpi = false           -- 允许在视网膜显示器(Retina)下使用高DPI模式 (boolean)
    t.window.x = nil                    -- 指定显示中窗口位置的 x坐标 (number)
    t.window.y = nil                    -- 指定显示中窗口位置的 y坐标 (number)
 
    t.modules.audio = true             -- 加载 audio        模块 (boolean)
    t.modules.data = true               -- 加载 data        模块 (boolean)
    t.modules.event = true             -- 加载 event        模块 (boolean)
    t.modules.font = true               -- 加载 font        模块 (boolean)
    t.modules.graphics = true          -- 加载 graphics     模块 (boolean)
    t.modules.image = true             -- 加载 image        模块 (boolean)
    t.modules.joystick = true          -- 加载 the joystick 模块 (boolean)
    t.modules.keyboard = true          -- 加载 keyboard     模块 (boolean)
    t.modules.math = true              -- 加载 math         模块 (boolean)
    t.modules.mouse = true             -- 加载 mouse        模块 (boolean)
    t.modules.physics = true           -- 加载 physics      模块 (boolean)
    t.modules.sound = true             -- 加载 sound        模块 (boolean)
    t.modules.system = true            -- 加载 system       模块 (boolean)
    t.modules.thread = true             -- 加载 thread       模块 (boolean)
    t.modules.timer = true             -- 加载 timer        模块 (boolean)，取消加载此模块会导致 love.update 中 delta time 为 0
    t.modules.touch = true              -- 加载 touch       模块 (boolean)
    t.modules.video = true              -- 加载 video       模块 (boolean)
    t.modules.window = true            -- 加载 window       模块 (boolean)
end
